{
 "title": "Solr dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Indexing throughput (requests / sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UPDATE./update.requestTimes",
     "query": "SELECT mean(\"one-minute\") /60 FROM \"UPDATE./update.requestTimes\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "one-minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indexing throughput (docs/seq)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UPDATE.updateHandler.cumulativeAdds",
     "select": [
      [
       { "params": [ "one-minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "QUERY./select.requestTimes",
     "query": "SELECT mean(\"99-percentile\"), mean(\"95-percentile\")  FROM \"QUERY./select.requestTimes\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "99-percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "QUERY./select.requestTimes",
     "select": [
      [
       { "params": [ "one-minute" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(*) FROM \"CONTAINER.overseer.stateUpdates\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(*) FROM \"CONTAINER.overseer.stateUpdates\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}